/*
 * This file is generated by jOOQ.
 */
package io.github.nightcalls.echochamber.channel.repository.jooq.tables.records;


import io.github.nightcalls.echochamber.channel.repository.jooq.tables.Channel;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelRecord extends UpdatableRecordImpl<ChannelRecord> implements Record6<Long, String, Long, OffsetDateTime, OffsetDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>c.channel.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>c.channel.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>c.channel.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>c.channel.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>c.channel.owner_id</code>.
     */
    public void setOwnerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>c.channel.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>c.channel.created_ts</code>.
     */
    public void setCreatedTs(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>c.channel.created_ts</code>.
     */
    public OffsetDateTime getCreatedTs() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>c.channel.updated_ts</code>.
     */
    public void setUpdatedTs(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>c.channel.updated_ts</code>.
     */
    public OffsetDateTime getUpdatedTs() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>c.channel.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>c.channel.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Long, OffsetDateTime, OffsetDateTime, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Long, OffsetDateTime, OffsetDateTime, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Channel.CHANNEL.ID;
    }

    @Override
    public Field<String> field2() {
        return Channel.CHANNEL.NAME;
    }

    @Override
    public Field<Long> field3() {
        return Channel.CHANNEL.OWNER_ID;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Channel.CHANNEL.CREATED_TS;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Channel.CHANNEL.UPDATED_TS;
    }

    @Override
    public Field<Boolean> field6() {
        return Channel.CHANNEL.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getOwnerId();
    }

    @Override
    public OffsetDateTime component4() {
        return getCreatedTs();
    }

    @Override
    public OffsetDateTime component5() {
        return getUpdatedTs();
    }

    @Override
    public Boolean component6() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getOwnerId();
    }

    @Override
    public OffsetDateTime value4() {
        return getCreatedTs();
    }

    @Override
    public OffsetDateTime value5() {
        return getUpdatedTs();
    }

    @Override
    public Boolean value6() {
        return getDeleted();
    }

    @Override
    public ChannelRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ChannelRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ChannelRecord value3(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public ChannelRecord value4(OffsetDateTime value) {
        setCreatedTs(value);
        return this;
    }

    @Override
    public ChannelRecord value5(OffsetDateTime value) {
        setUpdatedTs(value);
        return this;
    }

    @Override
    public ChannelRecord value6(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public ChannelRecord values(Long value1, String value2, Long value3, OffsetDateTime value4, OffsetDateTime value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelRecord
     */
    public ChannelRecord() {
        super(Channel.CHANNEL);
    }

    /**
     * Create a detached, initialised ChannelRecord
     */
    public ChannelRecord(Long id, String name, Long ownerId, OffsetDateTime createdTs, OffsetDateTime updatedTs, Boolean deleted) {
        super(Channel.CHANNEL);

        setId(id);
        setName(name);
        setOwnerId(ownerId);
        setCreatedTs(createdTs);
        setUpdatedTs(updatedTs);
        setDeleted(deleted);
    }
}
