/*
 * This file is generated by jOOQ.
 */
package io.github.nightcalls.echochamber.channel.repository.jooq;


import io.github.nightcalls.echochamber.channel.repository.jooq.tables.Channel;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class C extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>c</code>
     */
    public static final C C = new C();

    /**
     * The table <code>c.channel</code>.
     */
    public final Channel CHANNEL = Channel.CHANNEL;

    /**
     * No further instances allowed
     */
    private C() {
        super("c", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CHANNEL_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Channel.CHANNEL);
    }
}
