/*
 * This file is generated by jOOQ.
 */
package io.github.nightcalls.echochamber.channel.repository.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in c.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>c.channel_id_seq</code>
     */
    public static final Sequence<Long> CHANNEL_ID_SEQ = Internal.createSequence("channel_id_seq", C.C, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
