/*
 * This file is generated by jOOQ.
 */
package io.github.nightcalls.echochamber.channel.repository.jooq;


import io.github.nightcalls.echochamber.channel.repository.jooq.tables.Channel;


/**
 * Convenience access to all tables in c.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>c.channel</code>.
     */
    public static final Channel CHANNEL = Channel.CHANNEL;
}
