/*
 * This file is generated by jOOQ.
 */
package echochamber.user.repository.jooq;


import echochamber.user.repository.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class U extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>u</code>
     */
    public static final U U = new U();

    /**
     * The table <code>u.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private U() {
        super("u", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
