/*
 * This file is generated by jOOQ.
 */
package io.github.nightcalls.echochamber.channel.repository.jooq.tables;


import io.github.nightcalls.echochamber.channel.repository.jooq.C;
import io.github.nightcalls.echochamber.channel.repository.jooq.Keys;
import io.github.nightcalls.echochamber.channel.repository.jooq.tables.records.ChannelRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Channel extends TableImpl<ChannelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>c.channel</code>
     */
    public static final Channel CHANNEL = new Channel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChannelRecord> getRecordType() {
        return ChannelRecord.class;
    }

    /**
     * The column <code>c.channel.id</code>.
     */
    public final TableField<ChannelRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>c.channel.name</code>.
     */
    public final TableField<ChannelRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>c.channel.owner_id</code>.
     */
    public final TableField<ChannelRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>c.channel.created_ts</code>.
     */
    public final TableField<ChannelRecord, OffsetDateTime> CREATED_TS = createField(DSL.name("created_ts"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>c.channel.updated_ts</code>.
     */
    public final TableField<ChannelRecord, OffsetDateTime> UPDATED_TS = createField(DSL.name("updated_ts"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>c.channel.deleted</code>.
     */
    public final TableField<ChannelRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    private Channel(Name alias, Table<ChannelRecord> aliased) {
        this(alias, aliased, null);
    }

    private Channel(Name alias, Table<ChannelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>c.channel</code> table reference
     */
    public Channel(String alias) {
        this(DSL.name(alias), CHANNEL);
    }

    /**
     * Create an aliased <code>c.channel</code> table reference
     */
    public Channel(Name alias) {
        this(alias, CHANNEL);
    }

    /**
     * Create a <code>c.channel</code> table reference
     */
    public Channel() {
        this(DSL.name("channel"), null);
    }

    public <O extends Record> Channel(Table<O> child, ForeignKey<O, ChannelRecord> key) {
        super(child, key, CHANNEL);
    }

    @Override
    public Schema getSchema() {
        return C.C;
    }

    @Override
    public Identity<ChannelRecord, Long> getIdentity() {
        return (Identity<ChannelRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ChannelRecord> getPrimaryKey() {
        return Keys.CHANNEL_PKEY;
    }

    @Override
    public List<UniqueKey<ChannelRecord>> getKeys() {
        return Arrays.<UniqueKey<ChannelRecord>>asList(Keys.CHANNEL_PKEY);
    }

    @Override
    public Channel as(String alias) {
        return new Channel(DSL.name(alias), this);
    }

    @Override
    public Channel as(Name alias) {
        return new Channel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Channel rename(String name) {
        return new Channel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Channel rename(Name name) {
        return new Channel(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Long, OffsetDateTime, OffsetDateTime, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
