/*
 * This file is generated by jOOQ.
 */
package io.github.nightcalls.echochamber.user.repository.jooq;


import io.github.nightcalls.echochamber.user.repository.jooq.tables.User;


/**
 * Convenience access to all tables in u.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>u.user</code>.
     */
    public static final User USER = User.USER;
}
